-- NUMBER ONE A-- 
SELECT *
FROM CUSTOMER, INVOICE, INVOICE_ITEM;

-- NUMBER TWO B-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER;

-- NUMBER THREE C-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE FIRSTNAME = 'Nikki';

-- NUMBER FOUR D-- 
SELECT LASTNAME, FIRSTNAME, PHONE, DATEIN, DATEOUT
FROM CUSTOMER, INVOICE
WHERE TotalAmount > 100;

-- NUMBER FIVE E-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE FIRSTNAME LIKE 'B%';

-- NUMBER SIX F-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE LASTNAME LIKE 'cat%';

-- NUMBER SEVEN G-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE PHONE LIKE '%23%';

-- NUMBER EIGHT H-- 
SELECT MAX(TOTALAMOUNT) AS MAXIMUM_AMOUNT,
MIN(TOTALAMOUNT) AS MINIMUM_AMOUNT
FROM INVOICE;

-- NUMBER NINE I-- 
SELECT AVG(TOTALAMOUNT) AS AVERAGE_TOTALAMOUNT
FROM INVOICE;

-- NUMBER TEN J-- 
SELECT COUNT(FIRSTNAME) AS NUMBER_OF_CUSTOMERS
FROM CUSTOMER;

-- NUMBER ELEVEN K-- 
SELECT LASTNAME, FIRSTNAME
FROM CUSTOMER
group by LASTNAME, FIRSTNAME;

-- NUMBER TWELVE L-- 
SELECT LASTNAME, FIRSTNAME, COUNT(*) AS MATCHINGNAMES
FROM CUSTOMER
GROUP BY LASTNAME, FIRSTNAME;

-- NUMBER ELEVEN-- 

-- NUMBER TWELVE-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER, INVOICE
WHERE CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
AND INVOICE.TOTALAMOUNT > 100
ORDER BY CUSTOMER.LASTNAME ASC, CUSTOMER.FIRSTNAME DESC;

-- NUMBER THIRTEEN-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
WHERE INVOICE.TOTALAMOUNT > 100
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

-- NUMBER FOURTEEN-- 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE CUSTOMERID IN (
	SELECT CUSTOMERID
    FROM INVOICE
    WHERE INVOICENUMBER IN (
		SELECT INVOICENUMBER
        FROM INVOICE_ITEM
        WHERE ITEM = 'Dress Shirt'
    )
)
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

-- NUMBER FIFTEEN--
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER, INVOICE, INVOICE_ITEM
WHERE CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
AND INVOICE.INVOICENUMBER.ITEM = INVOICE_ITEM.INVOICENUMBER
AND INVOICE_ITEM